### ISSUE TITLE
Click on a snippet must select the same snippet on the text

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1160]
**TODO**

- [ ] Remove snippet's highlight by default. Now is hard to read the document with all yellow, and those highlights are not giving any value to the users. **Just the keywords** must be highlighted in yellow by default.
- [ ] When click on the page number next the snippets, that snippet must be selected with blue background.
- [ ] When a snippet in selected on the sidepanel, the same snippet is selected in the document. Keep the keywords highlighted in yellow, and make the rest of the snippet blue.

All the styles are ready on `1115-highlights` branch. [This is the current state of that branch](https://user-images.githubusercontent.com/6364153/28418021-8682d2f0-6d5a-11e7-958b-3a0656f0c330.png), so I suggest continue working on that branch and implement the other features on the top of those styles.

**Design preview**

![final-design](https://user-images.githubusercontent.com/6364153/28418022-86854012-6d5a-11e7-8939-a2610abcb862.png)
