### ISSUE TITLE
Support multiple languages on Violated articles headers

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1258]
Right now, synced Violated articles table share the same header in the input language (Spanish). We should add automatic translation to those headers.

Also the violated articles headers are acronyms (cidfp, cadh, cipst). Experienced users will understand the acronyms but not new ones.

With tooltips we can:

- Show the complete name while hover the header.
- Show the translated name in different languages while hover the header.

@txau @konzz how are we going to manage this translations? Are they going to be hardcoded?

## TODO

- [x] Request a list of all instruments supported by Violated articles.
- [ ] Automatic translation for headers (both acronyms and full name).
- [ ] Add tooltip that renders full name when the cursor is hover the acronym.
