### ISSUE TITLE
Relationships hub todo

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#1430]
- [x] Fix filters
- [x] Fix text references creation and ensure that they are correctly rendered in the new view
- [x] Review relationships creation from metadata
- [x] Show new relationships view in documents
- [x] Fix thesauris listings
- [x] Finish save process in relationship view (this includes reloading the relationships and ensuring that values on totals, on aggregations, etc. are updated upon save)
- [x] Add 'view' or 'go' button to the sidepanel metadata on relationships view
- [x] Show metada of the entity when selected
- [x] Show cards collapsed. No expand button.
- [x] If it is a text reference, show the snippet text on the collapsed card.
- [x] Fix issue: on first run, when refreshing on library, navigating to entity and then switching to connections, there are no relationshipTypes in store and rendering fails. (entities done, check documents)
- [x] Make saving metadata reload relationships to reflect new aggregations and numbers
- [x] Add 'Any entity or document' option to relationship field select option
- [x] In Library, when clicking a card, the sidepanel shows tabs with 0 connections.  Fix this. (First approach: remove tab from sidepanel)
- [x] Languages on text relationships
- [x] Reset UI variables so that when you navigate to a different document/entity you are not seeing the relationships panel. (this could be better, specially when selecting VIEW from a sidepanel relationship entity, the pane is kept under relationships, instead of metadata)
- [x] Create blank state for relationships side panel
- [x] Remove double footer in document view for relationships
- [ ] Make sure all is TESTED!!!!
