### ISSUE TITLE
Rethink connections

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#425]
We need to inform users what kind of connection the document has:

![screenshot 2016-09-16 18 46 47](https://cloud.githubusercontent.com/assets/6364153/18593937/ef5a6c84-7c3d-11e6-9ab0-896daa464089.png)

We need the following styles:

**Inbound**
- A document pointing to current document.
- A paragraph pointing to current document.
- A document pointing to a paragraph on current document. 
- A paragraph pointing to a paragraph on current document. 

**Outbound**
- Current document pointing to other document.
- Current document pointing to a paragraph.
- A paragraph on current document pointing to other document.
- A paragraph on current document pointing to a paragraph on other document.

**Internal**
- A paragraph on current document pointing to other paragraph on the current document.

Note: I have not mentioned entities because they will be styled as whole documents.

We also need to render the **connection type** (Instrumented violated, etc), that is related to the connection way (if it's inbound or outbound).

**Comment by danicatalan** [comment]
We've been playing with some cool concepts on how to represent "a connection". This is the most accurate approach to the final UI that we get on the meeting:

![screenshot 2016-09-16 20 44 26](https://cloud.githubusercontent.com/assets/6364153/18597531/ca4c96ea-7c4e-11e6-8fec-f6812a0d8860.png)

**Comment by txau** [comment]
@danicatalan add latests designs here please

**Comment by danicatalan** [comment]
This card depends on #635, #712 and #713 (some improvements on those issues will affect on this one)

We've been talking to do the next improvements in connections:

- [ ] Show the connection tabs on library (related to #635).
- [ ] Keep document viewer opened (related to #713) to maintain the same interactive behaviour on entities and documents. On documents, the first opened tab will be the TOC. We still need to discuss which tab will be opened by default on entities (ideas are welcome).
- [ ] Connections sidepanel will be rendered with the same UI in all views (library, entities and documents). Initially we will keep the entities design because is the more completed one, but we can improve this in a new design iteration. The important fact here is to remove duplicates and make an even interface, with same interactions through all the UI.
- [ ] We will add an "advance search button" on the footer to expand the connections as a library search (view draft screenshots). We still need to figure how to design some actions, like switch between connection results and entity metadata/document viewer, or how do a clear difference between library search and connection search.
**Library search**
![clean filters blank](https://cloud.githubusercontent.com/assets/6364153/21614705/c95441d4-d1da-11e6-8086-2ba444d7dc70.png)
**Entity search inside "Alvarez y otros"**
![entity back button](https://cloud.githubusercontent.com/assets/6364153/21614690/bc6ae874-d1da-11e6-9466-58216537b8c4.png)
- [ ] Keep in mind that in those screenshots we've remove the tabs, but related to #712 the searchbar will be in top of the filters and we will keep those tabs upside the searchbar.

I'm gonna work with other issues before coming back to this one hoping that some of related cards (#635, #712, #713) will be merged and we will perform accurate interactions and create new mocks with more fidelity on top of those features.

**Comment by danicatalan** [comment]
This is a further step on the connections design process (with a lot of screenshots).

First of all, we have the **Library**. When our document list is displayed by default, the sidepanel is integrated with the library, so we remove the background to this sidepanel to achieve this feeling.

![library](https://cloud.githubusercontent.com/assets/6364153/22181445/fc11709a-e08c-11e6-950f-af910a29029c.png)

From this step, everytime we open a sidepanel this must be white. This give the sidepanel a feeling of "modal" view that can be displayed/closed. We will keep this everytime a sidepanel with document information is displayed (library, document viewer or entity viewer) and we will play with this to differentiate between library results and document / entity connection results.

So if we open a sidepanel on library, it will render like this:

![library-toc](https://cloud.githubusercontent.com/assets/6364153/22181469/93e5efe0-e08d-11e6-892a-216880b28706.png)
![library-info](https://cloud.githubusercontent.com/assets/6364153/22181468/93e193a0-e08d-11e6-9b04-fd9cf96a22ab.png)
![library-connections](https://cloud.githubusercontent.com/assets/6364153/22181471/a790cd9e-e08d-11e6-8bd7-0c4211ba6a76.png)

At this step, we are showing a modified view of our filter section. We display the filters according to the document/entity connections. If the entity itself is a filter (for example, Country), this filter must be removed from the list, because we already filtered with this property.

When the user performs a search (with the searchbox, filters or clicking the Search button), the left panel changes and shows the connections lists related to this document/entity.

![library-connections-opened](https://cloud.githubusercontent.com/assets/6364153/22181490/0405be5e-e08e-11e6-8f8c-a0e4ad0d0dbf.png)

You can notice that there's a little bar fixed at the top of the connections lists. This will be used as "breadcrumb" (not really a breadcrumb because we don't strictly follow a hierarchical navigation, but the purpose is to let know the user where he is). This will let the user quickly close this panel view and return to the previous state. I think this will be a great component and we can improve the functionality of it on future iterations (use it on other sections like settings), but we need to keep it simple right now for implementation purposes.

On the **Document viewer** the interaction is basically the same as in Library:

![document-toc](https://cloud.githubusercontent.com/assets/6364153/22181521/a4ce65a2-e08e-11e6-8d0c-c84ecedb4e8b.png)
![document-info](https://cloud.githubusercontent.com/assets/6364153/22181522/a4d05394-e08e-11e6-91b2-a4bc5f36c52f.png)
![document-connections](https://cloud.githubusercontent.com/assets/6364153/22181523/a4d05eb6-e08e-11e6-9ae6-9ee1299a66ab.png)
![document-connections-opened](https://cloud.githubusercontent.com/assets/6364153/22181527/b1604506-e08e-11e6-953a-a54b9e922e60.png)

The most complex part is on **Entity viewer** because we use a common tab (Info) on the left panel. We've decided to display the connection list on the Info panel. If the user clicks on the Connections tab, performs a search or use any filter, the left panel automatically switches to the document list:

![entity-info](https://cloud.githubusercontent.com/assets/6364153/22181548/30c61938-e08f-11e6-8067-3f8a7d36de19.png)
![entity-connections](https://cloud.githubusercontent.com/assets/6364153/22181547/30c3a194-e08f-11e6-9841-cec296054eb2.png)

Some ideas for future steps:
- [ ] Extend breadcrumbs through all the application.
- [ ] Improve the use of colours to help users understand if they are on library, document or entity view (related to #422).
- [ ] Study in/out animations for sidepanel, breadcrumbs and connections to improve usability.

**Comment by danicatalan** [comment]
Library flow:
![image](https://cloud.githubusercontent.com/assets/6364153/22206553/0acdb00e-e17c-11e6-80e1-6b5254609b3b.png)

Document flow:
![image](https://cloud.githubusercontent.com/assets/6364153/22206569/1e318bfc-e17c-11e6-86e2-377d1f286585.png)

Entity flow:
![image](https://cloud.githubusercontent.com/assets/6364153/22206581/25a68f68-e17c-11e6-8c97-779fbb3ab9dc.png)

**Comment by txau** [comment]
@danicatalan we are missing the connections panel. In the screenshots I see the same filters as in library. Its not a view on connections.

**Comment by danicatalan** [comment]
# Entities

Users can access to entity information through two views:

## Library viewer

On library, the information related to the selected card is displayed always on the sidepanel. Never an action will take effect on the main panel (the left one), except the library filters.

Entity info viewed on Library:
![library-info](https://cloud.githubusercontent.com/assets/6364153/22340569/3078d6c0-e3ee-11e6-8783-43a174e889fa.png)

Entity connections viewed on Library:
![library-connections](https://cloud.githubusercontent.com/assets/6364153/22340570/307c5ef8-e3ee-11e6-9f25-633cc18593d5.png)

Keep in mind this sidepanel never makes any change on the main panel, so all the interactions (click on a connection, click on search button...) will be **links** to the proper data displayed on the Entity viewer.

## Entity viewer

The main difference between is the entity info placement. In this case, the properties are rendered on the main panel. We use the right panel to show the connections as an statistic information (type of connections, number of related documents...).

Entity info viewed on Entity viewer:
![entity-info](https://cloud.githubusercontent.com/assets/6364153/22340567/30769d2e-e3ee-11e6-80f4-bfcfa6e3e6ba.png)

This sidepanel remains opened when the user clicks on Connections tab. Instead of changing the sidepanel, the main panel switches to the connections list. If a user clicks again on Info tab, he will go back to the main panel with properties.

Entity connections viewed on Entity viewer:
![entity-connections](https://cloud.githubusercontent.com/assets/6364153/22340565/3075bcd8-e3ee-11e6-9569-c47b1486c975.png)

## User flow

I added a recap with all the flows:

- If user is on Library and clicks on a connection, he will go to the Entity viewer > Connections tab with that connection activated and the main panel will render the proper cards.
- If user is on Entity and clicks on a connection, he will go to the Entity viewer > Connections tab with that connection activated and the main panel will render the proper cards.

![image](https://cloud.githubusercontent.com/assets/6364153/22340970/7d982bee-e3ef-11e6-8088-a4ea34cd2e65.png)

**Comment by danicatalan** [comment]
# Documents

For documents, the library view is pretty much the same as entities, so I will skip that part. Please let me know if you have any doubt and I will clarify it. 

This time I will focus just on the user flow.

In this case, we have a document on the main panel. All the tabs will change the sidepanel as usual. When the user starts using the connections, they will be rendered at the main panel, hiding the document.

To come back to the document, the user just have to click on any tab: this will hide the connection list and reset all the states to the default.

![image](https://cloud.githubusercontent.com/assets/6364153/22342773/d59c5b7a-e3f5-11e6-9ded-9b15c73f9ac9.png)

**Comment by danicatalan** [comment]
- [x] Render entity title and type on topbar.
- [ ] Render document title and type on topbar.
- [ ] Remove title and type from sidepanels on entity viewer and document viewer (keep on library).
- [ ] Change Connections tab. Display has filters (First level > Connection type, Second level > Document type).
- [ ] Load item lists after selecting a connection or document type.
- [ ] Hide item lists if user changes to another tab.

**Comment by RafaPolit** [comment]
I still believe that having the right pane tabs change the left hand content (while keeping the right-hand content static! - this is key!) is the wrong approach.

The argument that in other places the tabs are changing the left AS WELL as the content on the right is true, but they are ALSO changing the content beneath them!  In this case, the "i" button would ONLY change the left hand content, not the right hand.

With that in mind, what if we use a 'hybrid' approach:
![rethinkingconnections-info](https://cloud.githubusercontent.com/assets/4309019/22482420/ed8aacb2-e7c6-11e6-97a5-1f3b0a094f96.jpg)

![rethinkingconnections-library](https://cloud.githubusercontent.com/assets/4309019/22482421/ed906e7c-e7c6-11e6-9c47-dc60ab368d00.jpg)

This holds some additional advantages: 
- We could show attachments AND connections simultaneously, which can't be accomplished right now.
- We provide a solution that works for mobile devices as well (actually, how would the former option be resolved in mobile?)
- We can provide the same solution in Document view, instead of the "i" we put a "document" icon.  Again, connections can be seen while showing the TOC or the metadata in the left hand panel.

Looking for feedback,
Regards,
Rafa.

**Comment by RafaPolit** [comment]
Alternatively, this could be a new sliding panel, that is triggered by a single 'library' icon.  This button doesn't 'replace' the inner content, but pulls over a new sliding panel with the connections:

![rethinkingconnectionsslidingpanel](https://cloud.githubusercontent.com/assets/4309019/22514417/39b2751a-e86d-11e6-8a68-8d82396d8ecb.jpg)

It has to be thought how this would translate into mobile.

**Comment by txau** [comment]
@RafaPolit lets discuss this over a call. Its a big decision.

**Comment by RafaPolit** [comment]
This is what we came up with during the conversation, any further discussion is welcome:
![rethinkingconnections-singlebar](https://cloud.githubusercontent.com/assets/4309019/22557088/5b19af78-e937-11e6-9da6-790e14c7e8e0.jpg)

**Comment by txau** [comment]
I think this is good to go for now. We will need to iterate this further in the future.

**Comment by RafaPolit** [comment]
To discuss:
- [ ] Search box and aggregations: Should the number reflect the changes? how to show that there are more documents from a type but you are actually 'filtering' by text also.

**Comment by RafaPolit** [comment]
@danicatalan How are we going to DELETE connections on this new design?

**Comment by RafaPolit** [comment]
@txau @danicatalan 
Now that we have a working implementation, I have the feeling that the combo of 'aggregations' on the right and just plain 'documents' on the left is lacking information of what is the ACTUAL relationship between the document and the parent entity.

We have a summary on the right that says: "you have 5 documents of type X related to the entity", but on the list, it is not clear which are which, at all!

We may need to further develop the documents display.  What do you guys think?
